version: "3.3"

name: magna-home-task

services:
  db-saas:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: navilla
      POSTGRES_USER: navilla
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
